version: "3.9"

services:
  db:
    image: postgres:buster
    container_name: ocl-db-postgres
    volumes:
      - ./docker-entrypoint-initdb.d/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data/db:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_DB=ocl_database
      - POSTGRES_USER=ocl_user
      - POSTGRES_PASSWORD=ocl_password
  web:
    container_name: ocl-web
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    restart: always
    environment:
      SECRET_KEY=$SECRET_KEY
      DB_NAME=$DB_NAME
      DB_USER=$DB_USER
      DB_PASSWORD=$DB_PASSWORD
      DB_HOST=$DB_HOST
      DB_PORT=$DB_PORT
    depends_on:
      - db

