version: "3.9"

services:
  db:
    image: postgres:buster
    container_name: ocl-db-postgres
    volumes:
      - ./docker-entrypoint-initdb.d/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=ocl_database
      - POSTGRES_USER=ocl_user
      - POSTGRES_PASSWORD=ocl_password
  web:
    container_name: ocl-web
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    depends_on:
      - db
steps:
  - name: Checkout source
  uses: actions/checkout@v1
  - name: Create role
  run: docker exec ocl-db-postgres bash -c "CREATE USER example WITH PASSWORD 'ocl_password';"
  run: docker exec ocl-db-postgres bash -c "CREATE DATABASE ocl_database;"
  run: docker exec ocl-db-postgres bash -c "GRANT ALL PRIVILEGES ON DATABASE ocl_database TO example;"
