version: "3.9"

services:
  db:
    image: postgres:buster
    volumes:
      - ./docker-entrypoint-initdb.d/init.sh:/docker-entrypoint-initdb.d/
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=ocl_database
      - POSTGRES_USER=ocl_user
      - POSTGRES_PASSWORD=ocl_password
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    depends_on:
      - db
