version: "3.9"

services:
  db:
    image: postgres:buster
    container_name: ocl-db-postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    restart: always
    environment:
      - POSTGRES_DB=ocl_database
      - POSTGRES_USER=example
      - POSTGRES_PASSWORD=ocl_password
  web:
    container_name: ocl-web
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    env_file:
      - .env
    restart: always
    depends_on:
      - db
    image: lucky3d/cci_ocl:${TAG}

