version: 2.1

jobs:
  pytest-and-flake:
    docker:
      - image: cimg/python:3.9.1
    steps:
      - checkout
      - run:
          name: install dependencies
          command: pip install -r requirements.txt
      - run:
          name: flake8 checker
          command: flake8 ./ --output-file test-reports.txt
      - run:
          name: run tests
          command: pytest -s

workflows:
  build-and-test-workflow:
    jobs:
      - pytest-and-flake