version: 2.1
orbs:
  heroku: circleci/heroku@1.2.6
jobs:
  pytest-and-flake:
    docker:
      - image: cimg/python:3.9.1
      - image: cimg/postgres:14.1
        environment:
          DB_USER: $DB_USER
          DB_PASSWORD: $DB_PASSWORD
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install postgresql-client
      - run: psql --version
      - run: |
          psql -h localhost -U postgres -c "CREATE USER $DB_USER WITH PASSWORD '$DB_PASSWORD';"
          psql -h localhost -U postgres -c "CREATE DATABASE $DB_NAME;"
          psql -h localhost -U postgres -c "GRANT ALL PRIVILEGES ON DATABASE $DB_NAME TO $DB_USER;"
          psql -h localhost -U postgres -c "ALTER USER $DB_USER CREATEDB;"
      - run:
          name: check TEST environment variable
          command: echo $DB_TEST
      - run:
          name: install python packages
          command: pip install -r requirements.txt
      - run:
          name: flake8 checker
          command: flake8 ./ --output-file test-reports.txt
      - run:
          name: running migrations
          command: python manage.py migrate
      - run:
          name: run tests
          command: pytest -s
      - run:
          name: install docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin

workflows:
  build-and-test-workflow:
    jobs:
      - pytest-and-flake
      - heroku/deploy-via-git:
          requires:
            - pytest-and-flake
          filters:
            branches:
              only: main