version: 2.1

jobs:
  pytest-and-flake:
    docker:
      - image: circleci/python:3.9.1
        environment:
          ENV: CIRCLE
          DATABASE_URL: postgresql://circleci@localhost/circle_test
      - image: circleci/postgres:14.1
        environment:
          PGHOST: localhost
          PGUSER: circleci
          DB_USER: circleci
          DB_PASSWORD: $DB_PASSWORD
          DB_NAME: circle_test
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install postgresql-client
      - run: psql --version
      - run: |
          psql -h localhost -p 5432
          psql -c "CREATE USER $DB_USER WITH PASSWORD $DB_PASSWORD;"
          psql -c "GRANT ALL PRIVILEGES ON DATABASE $TEST_DATABASE_URL TO $DB_USER;"
          psql -c "ALTER ROLE $DB_USER WITH LOGIN;"
      - run:
          name: check TEST environment variable
          command: echo $DB_TEST
      - run:
          name: install python packages
          command: pip install -r requirements.txt
      - run:
          name: flake8 checker
          command: flake8 ./ --output-file test-reports.txt
      - run:
          name: running migrations
          command: python manage.py migrate
      - run:
          name: run tests
          command: pytest -s


workflows:
  build-and-test-workflow:
    jobs:
      - pytest-and-flake