version: 2.1
orbs:
  heroku: circleci/heroku@1.2.6
jobs:
  pytest-and-flake:
    docker:
      - image: cimg/python:3.9.1
      - image: cimg/postgres:14.1
        environment:
          DB_USER: $DB_USER
          DB_PASSWORD: $DB_PASSWORD
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build --tag helloworld .
      - run:
          name: flake8 checker
          command: flake8 ./ --output-file test-reports.txt
      - run:
          name: running migrations
          command: python manage.py migrate
      - run:
          name: run tests
          command: pytest -s


workflows:
  build-and-test-workflow:
    jobs:
      - pytest-and-flake
      - heroku/deploy-via-git:
          requires:
            - pytest-and-flake
          filters:
            branches:
              only: main