version: 2.1

jobs:
  pytest-and-flake:
    docker:
      - image: cimg/python:3.9.1
    steps:
      - checkout
      - run:
          name: install dependencies
          command: pip install -r requirements.txt
      - run:
          name: flake8 checker
          command: flake8 --format=html --htmldir=flake-report
      - run:
          name: run tests
          command: python manage.py pytest

workflows:
  build-and-test-workflow:
    jobs:
      - pytest-and-flake