version: 2.1
orbs:
  heroku: circleci/heroku@1.2.6
jobs:
  pytest-and-flake:
    docker:
      - image: cimg/python:3.9.1
      - image: cimg/postgres:14.1
        environment:
          DB_USER: $DB_USER
          DB_PASSWORD: $DB_PASSWORD
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install postgresql-client
      - run: psql --version
      - run: |
         psql -h localhost -U postgres -c "CREATE USER $DB_USER WITH PASSWORD '$DB_PASSWORD';"
         psql -h localhost -U postgres -c "CREATE DATABASE $DB_NAME;"
         psql -h localhost -U postgres -c "GRANT ALL PRIVILEGES ON DATABASE $DB_NAME TO $DB_USER;"
         psql -h localhost -U postgres -c "ALTER USER $DB_USER CREATEDB;"
      - run:
         name: check TEST environment variable
         command: echo $DB_TEST
      - run: |
          pip install --upgrade pip
          pip install -r requirements.txt
      - run:
         name: flake8 checker
         command: flake8 ./ --output-file test-reports.txt
      - run:
         name: running migrations
         command: python manage.py migrate
      - run:
         name: run tests
         command: pytest -s
      - setup_remote_docker
      # build and push Docker image
      #docker login -u $DOCKER_USER -p $DOCKER_PASS
      #docker-compose build --pull
      #docker-compose push
      #docker logout
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker-compose build --pull
          docker-compose run web python manage.py migrate
          docker-compose push
          docker logout

workflows:
  build-and-test-workflow:
    jobs:
      - pytest-and-flake
      - heroku/deploy-via-git:
          requires:
            - pytest-and-flake
          filters:
            branches:
              only: main