version: 2.1

jobs:
  pytest-and-flake:
    docker:
      - image: cimg/python:3.9.1
      - image: cimg/postgres:14.1
        environment:
          DB_USER: $DB_USER
          DB_PASSWORD: $DB_PASSWORD
    steps:
      - checkout
      - run:
          name : system update
          command : sudo apt-get update
      - run:
          name : install system packages
          command : sudo apt-get install postgresql-client
      - run: |
          sudo useradd -m -p $LX_PASSWORD -s /bin/bash postgres
          sudo -u postgres -i
          sudo -u postgres psql -c "CREATE USER $DB_USER WITH PASSWORD $DB_PASSWORD;"
          sudo -u postgres psql -c "CREATE DATABASE $DB_NAME;"
          sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE $DB_NAME TO $DB_USER;"

      - run:
          name: check TEST environment variable
          command: echo $DB_TEST
      - run:
          name: install python packages
          command: pip install -r requirements.txt
      - run:
          name: flake8 checker
          command: flake8 ./ --output-file test-reports.txt
      - run:
          name: running migrations
          command: python manage.py migrate
      - run:
          name: run tests
          command: pytest -s


workflows:
  build-and-test-workflow:
    jobs:
      - pytest-and-flake