version: 2.1

jobs:
  pytest-and-flake:
    docker:
      - image: cimg/python:3.9.1
        environment:
          TEST_DATABASE_URL: postgresql://postgres@localhost/example
      - image: cimg/postgres:14.1
        environment:
          DB_USER: $DB_USER
          DB_PASSWORD: $DB_PASSWORD
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install postgresql-client
      - run: psql --version
      - run: |
          psql -h localhost -U postgres -c "CREATE USER $DB_USER WITH PASSWORD '$DB_PASSWORD';"
          psql -h localhost -U postgres -c "GRANT ALL PRIVILEGES ON DATABASE $TEST_DATABASE_URL TO $DB_USER;"
      - run:
          name: check TEST environment variable
          command: echo $DB_TEST
      - run:
          name: install python packages
          command: pip install -r requirements.txt
      - run:
          name: flake8 checker
          command: flake8 ./ --output-file test-reports.txt
      - run:
          name: running migrations
          command: python manage.py migrate
      - run:
          name: run tests
          command: pytest -s


workflows:
  build-and-test-workflow:
    jobs:
      - pytest-and-flake